# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CS 131 Fall 2024
tagline: Course website for Fall 2024 CS 131 | Programming Languages at UCLA
description: Course website for Fall 2024 CS 131 | Programming Languages at UCLA
author: Matthew Wang, Ruining Ding, Brian Wang, Bonnie Liu
baseurl: '/fall-24-website' # the subpath of your site, e.g. /blog
url: 'https://ucla-cs-131.github.io/' # the base hostname & protocol for your site, e.g. http://example.com
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "vendor", "README.md", "_modules/to_change", 
"lectures/old"]

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.9.0
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  Website on GitHub:
    - 'https://github.com/UCLA-CS-131/fall-24-website'

nav_external_links:

  - title: Campuswire
    url: https://campuswire.com/c/GFBA7A8E4
  - title: Gradescope
    url: https://www.gradescope.com/courses/869551
  - title: Lecture Slides
    url: https://drive.google.com/drive/folders/1LoYIavpZMdKk3W_3YUzzYfrR6if4EtqM
  - title: Discussion Resources
    url: https://drive.google.com/drive/folders/1C36JJOtbb7dBU1hYbPuisS8m7dH6W4ff?usp=sharing
  - title: Barista
    url: https://barista-f23.fly.dev
  - title: Past Website
    url: https://ucla-cs-131.github.io/fall-23-website/

# Collections for website data
collections:
  staffers:
  modules:
  schedules:
  announcements:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      height: 300
      subpath: '/assets/images/'
      width: 300
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

liquid:
  error_mode: strict
  strict_filters: true

# Adds a "Back to Top" link
back_to_top: true
back_to_top_text: "Back to top"

# Adds the "Edit this page on GitHub" link to the footer of each page
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/UCLA-CS-131/spring-23" # NOTE: update this to your new repo!
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

# Callouts let you add vibrant UI elements to notes
# via markdown code like {: .note }
callouts_level: quiet
callouts:
  important:
    title: Important
    color: yellow
  new:
    title: New
    color: green
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red

# Mermaid is a JS library that renders figures from markdown.
# You may want to update this version; pick one from https://cdn.jsdelivr.net/npm/mermaid/
mermaid:
  version: "11.1.1"
